# Generated by Django 3.1.3 on 2020-12-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretpass', '0005_keychecker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keychecker',
            name='keyhash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
