# Generated by Django 3.1.6 on 2021-03-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretpass', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyChecker',
        ),
    ]
